apiVersion: apps/v1
kind: Deployment
metadata:
  name: apltesting
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLabels:
      app: apltesting
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: apltesting
        {{- if .Values.azure }}
        aadpodidbinding: apltesting-azure-kv
        {{- end }}
    spec:
      containers:
        - name: apltesting
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: APLTESTING_VERSION
              value: "{{ .Chart.AppVersion }}"
            - name: DEBUG
              value: "0"
            - name: SQL_ENGINE
              value: django.db.backends.postgresql
            - name: SQL_NAME
              value: "{{ .Values.db.name }}"
            - name: SQL_HOST
              value: "{{ .Values.db.host }}"
            - name: SQL_USER
              value: "{{ .Values.db.user }}"
          envFrom:
            - secretRef:
                name: apltesting-secret
          {{- if .Values.azure }}
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/etc/secrets"
              readOnly: true
          {{- end }}

      {{- if .Values.azure }}
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "apltesting-secretproviderclass"
      {{- end }}