apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apltesting-ingress
  namespace: "{{ .Release.Namespace }}"
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingressClass }}"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - "{{ .Values.hostname }}"
  rules:
    - host: "{{ .Values.hostname }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apltesting
                port:
                  number: 80
