# Generated by Django 3.1 on 2020-08-23 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=1024)),
                ('token', models.CharField(max_length=1024)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('EV', 'Evaluate'), ('FV', 'Final value'), ('EC', 'Equivalent code'), ('PO', 'Printed output')], default='FV', max_length=2)),
                ('repeat', models.PositiveSmallIntegerField()),
                ('template', models.TextField()),
                ('question_override', models.CharField(default=None, max_length=1024, null=True)),
                ('final_value_variable', models.CharField(default=None, max_length=64, null=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.SmallIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='testingapp.test')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1024)),
                ('questions', models.PositiveSmallIntegerField(default=0)),
                ('correct_answers', models.PositiveSmallIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='testingapp.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='testingapp.test')),
            ],
        ),
    ]
