# Generated by Django 3.1 on 2020-08-23 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='course_site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='testingapp.coursesite'),
            preserve_default=False,
        ),
    ]
