# Generated by Django 3.1 on 2020-08-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0002_attempt_course_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesite',
            name='active_tests',
            field=models.ManyToManyField(to='testingapp.Test'),
        ),
    ]
