# Generated by Django 3.1 on 2020-08-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0003_coursesite_active_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='final_value_variable',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_override',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Evaluate', 'Evaluate'), ('Final value', 'Final value'), ('Equivalent code', 'Equivalent code'), ('Printed output', 'Printed output')], default='Final value', max_length=16),
        ),
    ]
