FROM alpine:3.10

# Set work directory
WORKDIR /code

# Install psycopg2
RUN apk update \
    && apk add --virtual build-deps gcc python3 python3-dev musl-dev py3-pip py3-reportlab \
    && apk add postgresql-dev git \
    && pip3 install psycopg2

# Install packages
RUN pip3 install pipenv
COPY Pipfile Pipfile.lock /code/
RUN pipenv install --system

COPY ./docker-entrypoint.dev.sh /code/docker-entrypoint.dev.sh

ENTRYPOINT ["/code/docker-entrypoint.dev.sh"]
